/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class CampElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Camp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCampKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColorseniorsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cColorseniorsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cColorseniorsColorSeniorParserRuleCall_4_0 = (RuleCall)cColorseniorsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cCardseniorsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cCardseniorsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cCardseniorsCardSeniorParserRuleCall_8_0 = (RuleCall)cCardseniorsAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cRoomseniorsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cLeftCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cRoomseniorsAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cRoomseniorsRoomSeniorParserRuleCall_12_0 = (RuleCall)cRoomseniorsAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cColorsKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cLeftCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cColorsAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cColorsColorParserRuleCall_16_0 = (RuleCall)cColorsAssignment_16.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		
		//Camp:
		//	'camp' name=ID
		//	'colorseniors' '{'
		//	colorseniors+=ColorSenior*
		//	'}'
		//	'cardseniors' '{'
		//	cardseniors+=CardSenior*
		//	'}'
		//	'roomseniors' '{'
		//	roomseniors+=RoomSenior*
		//	'}'
		//	'colors' '{'
		//	colors+=Color*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'camp' name=ID 'colorseniors' '{' colorseniors+=ColorSenior* '}' 'cardseniors' '{' cardseniors+=CardSenior* '}'
		//'roomseniors' '{' roomseniors+=RoomSenior* '}' 'colors' '{' colors+=Color* '}'
		public Group getGroup() { return cGroup; }
		
		//'camp'
		public Keyword getCampKeyword_0() { return cCampKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'colorseniors'
		public Keyword getColorseniorsKeyword_2() { return cColorseniorsKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//colorseniors+=ColorSenior*
		public Assignment getColorseniorsAssignment_4() { return cColorseniorsAssignment_4; }
		
		//ColorSenior
		public RuleCall getColorseniorsColorSeniorParserRuleCall_4_0() { return cColorseniorsColorSeniorParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
		
		//'cardseniors'
		public Keyword getCardseniorsKeyword_6() { return cCardseniorsKeyword_6; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//cardseniors+=CardSenior*
		public Assignment getCardseniorsAssignment_8() { return cCardseniorsAssignment_8; }
		
		//CardSenior
		public RuleCall getCardseniorsCardSeniorParserRuleCall_8_0() { return cCardseniorsCardSeniorParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'roomseniors'
		public Keyword getRoomseniorsKeyword_10() { return cRoomseniorsKeyword_10; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_11() { return cLeftCurlyBracketKeyword_11; }
		
		//roomseniors+=RoomSenior*
		public Assignment getRoomseniorsAssignment_12() { return cRoomseniorsAssignment_12; }
		
		//RoomSenior
		public RuleCall getRoomseniorsRoomSeniorParserRuleCall_12_0() { return cRoomseniorsRoomSeniorParserRuleCall_12_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'colors'
		public Keyword getColorsKeyword_14() { return cColorsKeyword_14; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_15() { return cLeftCurlyBracketKeyword_15; }
		
		//colors+=Color*
		public Assignment getColorsAssignment_16() { return cColorsAssignment_16; }
		
		//Color
		public RuleCall getColorsColorParserRuleCall_16_0() { return cColorsColorParserRuleCall_16_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
	}
	public class FreshmanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Freshman");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameNameParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNeptunKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNeptunAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNeptunSTRINGTerminalRuleCall_4_0 = (RuleCall)cNeptunAssignment_4.eContents().get(0);
		private final Keyword cColorKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cColorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cColorColorTypeEnumRuleCall_7_0 = (RuleCall)cColorAssignment_7.eContents().get(0);
		private final Keyword cCardKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cCardAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cCardCardTypeEnumRuleCall_10_0 = (RuleCall)cCardAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Freshman:
		//	name=Name '{'
		//	'neptun' ':' neptun=STRING
		//	'color' ':' color=ColorType
		//	'card' ':' card=CardType
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=Name '{' 'neptun' ':' neptun=STRING 'color' ':' color=ColorType 'card' ':' card=CardType '}'
		public Group getGroup() { return cGroup; }
		
		//name=Name
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_0_0() { return cNameNameParserRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'neptun'
		public Keyword getNeptunKeyword_2() { return cNeptunKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//neptun=STRING
		public Assignment getNeptunAssignment_4() { return cNeptunAssignment_4; }
		
		//STRING
		public RuleCall getNeptunSTRINGTerminalRuleCall_4_0() { return cNeptunSTRINGTerminalRuleCall_4_0; }
		
		//'color'
		public Keyword getColorKeyword_5() { return cColorKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//color=ColorType
		public Assignment getColorAssignment_7() { return cColorAssignment_7; }
		
		//ColorType
		public RuleCall getColorColorTypeEnumRuleCall_7_0() { return cColorColorTypeEnumRuleCall_7_0; }
		
		//'card'
		public Keyword getCardKeyword_8() { return cCardKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//card=CardType
		public Assignment getCardAssignment_10() { return cCardAssignment_10; }
		
		//CardType
		public RuleCall getCardCardTypeEnumRuleCall_10_0() { return cCardCardTypeEnumRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class ColorSeniorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ColorSenior");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameNameParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cYearKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cYearAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cYearINTTerminalRuleCall_4_0 = (RuleCall)cYearAssignment_4.eContents().get(0);
		private final Keyword cColorKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cColorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cColorColorTypeEnumRuleCall_7_0 = (RuleCall)cColorAssignment_7.eContents().get(0);
		private final Keyword cInferiorsKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cInferiorsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cInferiorsCardSeniorCrossReference_10_0 = (CrossReference)cInferiorsAssignment_10.eContents().get(0);
		private final RuleCall cInferiorsCardSeniorNameParserRuleCall_10_0_1 = (RuleCall)cInferiorsCardSeniorCrossReference_10_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cInferiorsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cInferiorsCardSeniorCrossReference_11_1_0 = (CrossReference)cInferiorsAssignment_11_1.eContents().get(0);
		private final RuleCall cInferiorsCardSeniorNameParserRuleCall_11_1_0_1 = (RuleCall)cInferiorsCardSeniorCrossReference_11_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//ColorSenior:
		//	name=Name '{'
		//	//'school' ':' school=STRING
		//	'year' ':' year=INT
		//	'color' ':' color=ColorType
		//	'inferiors' ':' inferiors+=[CardSenior|Name] (',' inferiors+=[CardSenior|Name])*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=Name '{' //'school' ':' school=STRING
		//'year' ':' year=INT 'color' ':' color=ColorType 'inferiors' ':' inferiors+=[CardSenior|Name] (','
		//inferiors+=[CardSenior|Name])* '}'
		public Group getGroup() { return cGroup; }
		
		//name=Name
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_0_0() { return cNameNameParserRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		////'school' ':' school=STRING
		//'year'
		public Keyword getYearKeyword_2() { return cYearKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//year=INT
		public Assignment getYearAssignment_4() { return cYearAssignment_4; }
		
		//INT
		public RuleCall getYearINTTerminalRuleCall_4_0() { return cYearINTTerminalRuleCall_4_0; }
		
		//'color'
		public Keyword getColorKeyword_5() { return cColorKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//color=ColorType
		public Assignment getColorAssignment_7() { return cColorAssignment_7; }
		
		//ColorType
		public RuleCall getColorColorTypeEnumRuleCall_7_0() { return cColorColorTypeEnumRuleCall_7_0; }
		
		//'inferiors'
		public Keyword getInferiorsKeyword_8() { return cInferiorsKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//inferiors+=[CardSenior|Name]
		public Assignment getInferiorsAssignment_10() { return cInferiorsAssignment_10; }
		
		//[CardSenior|Name]
		public CrossReference getInferiorsCardSeniorCrossReference_10_0() { return cInferiorsCardSeniorCrossReference_10_0; }
		
		//Name
		public RuleCall getInferiorsCardSeniorNameParserRuleCall_10_0_1() { return cInferiorsCardSeniorNameParserRuleCall_10_0_1; }
		
		//(',' inferiors+=[CardSenior|Name])*
		public Group getGroup_11() { return cGroup_11; }
		
		//','
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }
		
		//inferiors+=[CardSenior|Name]
		public Assignment getInferiorsAssignment_11_1() { return cInferiorsAssignment_11_1; }
		
		//[CardSenior|Name]
		public CrossReference getInferiorsCardSeniorCrossReference_11_1_0() { return cInferiorsCardSeniorCrossReference_11_1_0; }
		
		//Name
		public RuleCall getInferiorsCardSeniorNameParserRuleCall_11_1_0_1() { return cInferiorsCardSeniorNameParserRuleCall_11_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class CardSeniorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CardSenior");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameNameParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cYearKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cYearAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cYearINTTerminalRuleCall_4_0 = (RuleCall)cYearAssignment_4.eContents().get(0);
		private final Keyword cColorKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cColorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cColorColorTypeEnumRuleCall_7_0 = (RuleCall)cColorAssignment_7.eContents().get(0);
		private final Keyword cCardKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cCardAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cCardCardTypeEnumRuleCall_10_0 = (RuleCall)cCardAssignment_10.eContents().get(0);
		private final Keyword cSuperiorKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cSuperiorAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final CrossReference cSuperiorColorSeniorCrossReference_13_0 = (CrossReference)cSuperiorAssignment_13.eContents().get(0);
		private final RuleCall cSuperiorColorSeniorNameParserRuleCall_13_0_1 = (RuleCall)cSuperiorColorSeniorCrossReference_13_0.eContents().get(1);
		private final Keyword cInferiorsKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cColonKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cInferiorsAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final CrossReference cInferiorsRoomSeniorCrossReference_16_0 = (CrossReference)cInferiorsAssignment_16.eContents().get(0);
		private final RuleCall cInferiorsRoomSeniorNameParserRuleCall_16_0_1 = (RuleCall)cInferiorsRoomSeniorCrossReference_16_0.eContents().get(1);
		private final Group cGroup_17 = (Group)cGroup.eContents().get(17);
		private final Keyword cCommaKeyword_17_0 = (Keyword)cGroup_17.eContents().get(0);
		private final Assignment cInferiorsAssignment_17_1 = (Assignment)cGroup_17.eContents().get(1);
		private final CrossReference cInferiorsRoomSeniorCrossReference_17_1_0 = (CrossReference)cInferiorsAssignment_17_1.eContents().get(0);
		private final RuleCall cInferiorsRoomSeniorNameParserRuleCall_17_1_0_1 = (RuleCall)cInferiorsRoomSeniorCrossReference_17_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//CardSenior:
		//	name=Name '{'
		//	//'school' ':' school=STRING
		//	'year' ':' year=INT
		//	'color' ':' color=ColorType
		//	'card' ':' card=CardType
		//	'superior' ':' superior+=[ColorSenior|Name]
		//	'inferiors' ':' inferiors+=[RoomSenior|Name] (',' inferiors+=[RoomSenior|Name])*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=Name '{' //'school' ':' school=STRING
		//'year' ':' year=INT 'color' ':' color=ColorType 'card' ':' card=CardType 'superior' ':' superior+=[ColorSenior|Name]
		//'inferiors' ':' inferiors+=[RoomSenior|Name] (',' inferiors+=[RoomSenior|Name])* '}'
		public Group getGroup() { return cGroup; }
		
		//name=Name
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_0_0() { return cNameNameParserRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		////'school' ':' school=STRING
		//'year'
		public Keyword getYearKeyword_2() { return cYearKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//year=INT
		public Assignment getYearAssignment_4() { return cYearAssignment_4; }
		
		//INT
		public RuleCall getYearINTTerminalRuleCall_4_0() { return cYearINTTerminalRuleCall_4_0; }
		
		//'color'
		public Keyword getColorKeyword_5() { return cColorKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//color=ColorType
		public Assignment getColorAssignment_7() { return cColorAssignment_7; }
		
		//ColorType
		public RuleCall getColorColorTypeEnumRuleCall_7_0() { return cColorColorTypeEnumRuleCall_7_0; }
		
		//'card'
		public Keyword getCardKeyword_8() { return cCardKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//card=CardType
		public Assignment getCardAssignment_10() { return cCardAssignment_10; }
		
		//CardType
		public RuleCall getCardCardTypeEnumRuleCall_10_0() { return cCardCardTypeEnumRuleCall_10_0; }
		
		//'superior'
		public Keyword getSuperiorKeyword_11() { return cSuperiorKeyword_11; }
		
		//':'
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }
		
		//superior+=[ColorSenior|Name]
		public Assignment getSuperiorAssignment_13() { return cSuperiorAssignment_13; }
		
		//[ColorSenior|Name]
		public CrossReference getSuperiorColorSeniorCrossReference_13_0() { return cSuperiorColorSeniorCrossReference_13_0; }
		
		//Name
		public RuleCall getSuperiorColorSeniorNameParserRuleCall_13_0_1() { return cSuperiorColorSeniorNameParserRuleCall_13_0_1; }
		
		//'inferiors'
		public Keyword getInferiorsKeyword_14() { return cInferiorsKeyword_14; }
		
		//':'
		public Keyword getColonKeyword_15() { return cColonKeyword_15; }
		
		//inferiors+=[RoomSenior|Name]
		public Assignment getInferiorsAssignment_16() { return cInferiorsAssignment_16; }
		
		//[RoomSenior|Name]
		public CrossReference getInferiorsRoomSeniorCrossReference_16_0() { return cInferiorsRoomSeniorCrossReference_16_0; }
		
		//Name
		public RuleCall getInferiorsRoomSeniorNameParserRuleCall_16_0_1() { return cInferiorsRoomSeniorNameParserRuleCall_16_0_1; }
		
		//(',' inferiors+=[RoomSenior|Name])*
		public Group getGroup_17() { return cGroup_17; }
		
		//','
		public Keyword getCommaKeyword_17_0() { return cCommaKeyword_17_0; }
		
		//inferiors+=[RoomSenior|Name]
		public Assignment getInferiorsAssignment_17_1() { return cInferiorsAssignment_17_1; }
		
		//[RoomSenior|Name]
		public CrossReference getInferiorsRoomSeniorCrossReference_17_1_0() { return cInferiorsRoomSeniorCrossReference_17_1_0; }
		
		//Name
		public RuleCall getInferiorsRoomSeniorNameParserRuleCall_17_1_0_1() { return cInferiorsRoomSeniorNameParserRuleCall_17_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
	}
	public class RoomSeniorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RoomSenior");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameNameParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cYearKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cYearAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cYearINTTerminalRuleCall_4_0 = (RuleCall)cYearAssignment_4.eContents().get(0);
		private final Keyword cColorKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cColorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cColorColorTypeEnumRuleCall_7_0 = (RuleCall)cColorAssignment_7.eContents().get(0);
		private final Keyword cCardKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cCardAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cCardCardTypeEnumRuleCall_10_0 = (RuleCall)cCardAssignment_10.eContents().get(0);
		private final Keyword cSuperiorKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cSuperiorAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final CrossReference cSuperiorCardSeniorCrossReference_13_0 = (CrossReference)cSuperiorAssignment_13.eContents().get(0);
		private final RuleCall cSuperiorCardSeniorNameParserRuleCall_13_0_1 = (RuleCall)cSuperiorCardSeniorCrossReference_13_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//RoomSenior:
		//	name=Name '{'
		//	//'school' ':' school=STRING
		//	'year' ':' year=INT
		//	'color' ':' color=ColorType
		//	'card' ':' card=CardType
		//	'superior' ':' superior+=[CardSenior|Name]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=Name '{' //'school' ':' school=STRING
		//'year' ':' year=INT 'color' ':' color=ColorType 'card' ':' card=CardType 'superior' ':' superior+=[CardSenior|Name] '}'
		public Group getGroup() { return cGroup; }
		
		//name=Name
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_0_0() { return cNameNameParserRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		////'school' ':' school=STRING
		//'year'
		public Keyword getYearKeyword_2() { return cYearKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//year=INT
		public Assignment getYearAssignment_4() { return cYearAssignment_4; }
		
		//INT
		public RuleCall getYearINTTerminalRuleCall_4_0() { return cYearINTTerminalRuleCall_4_0; }
		
		//'color'
		public Keyword getColorKeyword_5() { return cColorKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//color=ColorType
		public Assignment getColorAssignment_7() { return cColorAssignment_7; }
		
		//ColorType
		public RuleCall getColorColorTypeEnumRuleCall_7_0() { return cColorColorTypeEnumRuleCall_7_0; }
		
		//'card'
		public Keyword getCardKeyword_8() { return cCardKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//card=CardType
		public Assignment getCardAssignment_10() { return cCardAssignment_10; }
		
		//CardType
		public RuleCall getCardCardTypeEnumRuleCall_10_0() { return cCardCardTypeEnumRuleCall_10_0; }
		
		//'superior'
		public Keyword getSuperiorKeyword_11() { return cSuperiorKeyword_11; }
		
		//':'
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }
		
		//superior+=[CardSenior|Name]
		public Assignment getSuperiorAssignment_13() { return cSuperiorAssignment_13; }
		
		//[CardSenior|Name]
		public CrossReference getSuperiorCardSeniorCrossReference_13_0() { return cSuperiorCardSeniorCrossReference_13_0; }
		
		//Name
		public RuleCall getSuperiorCardSeniorNameParserRuleCall_13_0_1() { return cSuperiorCardSeniorNameParserRuleCall_13_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class OperativeOrganizerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.OperativeOrganizer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameNameParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cYearKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cYearAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cYearINTTerminalRuleCall_4_0 = (RuleCall)cYearAssignment_4.eContents().get(0);
		private final Keyword cColorKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cColorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cColorColorTypeEnumRuleCall_7_0 = (RuleCall)cColorAssignment_7.eContents().get(0);
		private final Keyword cSuperiorKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cSuperiorAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cSuperiorOperativeOrganizerCrossReference_10_0 = (CrossReference)cSuperiorAssignment_10.eContents().get(0);
		private final RuleCall cSuperiorOperativeOrganizerNameParserRuleCall_10_0_1 = (RuleCall)cSuperiorOperativeOrganizerCrossReference_10_0.eContents().get(1);
		private final Keyword cInferiorsKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cInferiorsAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final CrossReference cInferiorsOperativeOrganizerCrossReference_13_0 = (CrossReference)cInferiorsAssignment_13.eContents().get(0);
		private final RuleCall cInferiorsOperativeOrganizerNameParserRuleCall_13_0_1 = (RuleCall)cInferiorsOperativeOrganizerCrossReference_13_0.eContents().get(1);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cCommaKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cInferiorsAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final CrossReference cInferiorsOperativeOrganizerCrossReference_14_1_0 = (CrossReference)cInferiorsAssignment_14_1.eContents().get(0);
		private final RuleCall cInferiorsOperativeOrganizerNameParserRuleCall_14_1_0_1 = (RuleCall)cInferiorsOperativeOrganizerCrossReference_14_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//OperativeOrganizer:
		//	name=Name '{'
		//	//'school' ':' school=STRING
		//	'year' ':' year=INT
		//	'color' ':' color=ColorType
		//	'superior' ':' superior+=[OperativeOrganizer|Name]
		//	'inferiors' ':' inferiors+=[OperativeOrganizer|Name] (',' inferiors+=[OperativeOrganizer|Name])*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=Name '{' //'school' ':' school=STRING
		//'year' ':' year=INT 'color' ':' color=ColorType 'superior' ':' superior+=[OperativeOrganizer|Name] 'inferiors' ':'
		//inferiors+=[OperativeOrganizer|Name] (',' inferiors+=[OperativeOrganizer|Name])* '}'
		public Group getGroup() { return cGroup; }
		
		//name=Name
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_0_0() { return cNameNameParserRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		////'school' ':' school=STRING
		//'year'
		public Keyword getYearKeyword_2() { return cYearKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//year=INT
		public Assignment getYearAssignment_4() { return cYearAssignment_4; }
		
		//INT
		public RuleCall getYearINTTerminalRuleCall_4_0() { return cYearINTTerminalRuleCall_4_0; }
		
		//'color'
		public Keyword getColorKeyword_5() { return cColorKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//color=ColorType
		public Assignment getColorAssignment_7() { return cColorAssignment_7; }
		
		//ColorType
		public RuleCall getColorColorTypeEnumRuleCall_7_0() { return cColorColorTypeEnumRuleCall_7_0; }
		
		//'superior'
		public Keyword getSuperiorKeyword_8() { return cSuperiorKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//superior+=[OperativeOrganizer|Name]
		public Assignment getSuperiorAssignment_10() { return cSuperiorAssignment_10; }
		
		//[OperativeOrganizer|Name]
		public CrossReference getSuperiorOperativeOrganizerCrossReference_10_0() { return cSuperiorOperativeOrganizerCrossReference_10_0; }
		
		//Name
		public RuleCall getSuperiorOperativeOrganizerNameParserRuleCall_10_0_1() { return cSuperiorOperativeOrganizerNameParserRuleCall_10_0_1; }
		
		//'inferiors'
		public Keyword getInferiorsKeyword_11() { return cInferiorsKeyword_11; }
		
		//':'
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }
		
		//inferiors+=[OperativeOrganizer|Name]
		public Assignment getInferiorsAssignment_13() { return cInferiorsAssignment_13; }
		
		//[OperativeOrganizer|Name]
		public CrossReference getInferiorsOperativeOrganizerCrossReference_13_0() { return cInferiorsOperativeOrganizerCrossReference_13_0; }
		
		//Name
		public RuleCall getInferiorsOperativeOrganizerNameParserRuleCall_13_0_1() { return cInferiorsOperativeOrganizerNameParserRuleCall_13_0_1; }
		
		//(',' inferiors+=[OperativeOrganizer|Name])*
		public Group getGroup_14() { return cGroup_14; }
		
		//','
		public Keyword getCommaKeyword_14_0() { return cCommaKeyword_14_0; }
		
		//inferiors+=[OperativeOrganizer|Name]
		public Assignment getInferiorsAssignment_14_1() { return cInferiorsAssignment_14_1; }
		
		//[OperativeOrganizer|Name]
		public CrossReference getInferiorsOperativeOrganizerCrossReference_14_1_0() { return cInferiorsOperativeOrganizerCrossReference_14_1_0; }
		
		//Name
		public RuleCall getInferiorsOperativeOrganizerNameParserRuleCall_14_1_0_1() { return cInferiorsOperativeOrganizerNameParserRuleCall_14_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class ColorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Color");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameNameParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeColorTypeEnumRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Keyword cColorseniorKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cColorseniorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cColorseniorColorSeniorCrossReference_7_0 = (CrossReference)cColorseniorAssignment_7.eContents().get(0);
		private final RuleCall cColorseniorColorSeniorNameParserRuleCall_7_0_1 = (RuleCall)cColorseniorColorSeniorCrossReference_7_0.eContents().get(1);
		private final Keyword cCardsKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cCardsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cCardsCardParserRuleCall_10_0 = (RuleCall)cCardsAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Color:
		//	name=Name '{'
		//	'type' ':' type=ColorType
		//	'colorsenior' ':' colorsenior+=[ColorSenior|Name]
		//	'cards' '{'
		//	cards+=Card*
		//	'}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=Name '{' 'type' ':' type=ColorType 'colorsenior' ':' colorsenior+=[ColorSenior|Name] 'cards' '{' cards+=Card* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//name=Name
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_0_0() { return cNameNameParserRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'type'
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//type=ColorType
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//ColorType
		public RuleCall getTypeColorTypeEnumRuleCall_4_0() { return cTypeColorTypeEnumRuleCall_4_0; }
		
		//'colorsenior'
		public Keyword getColorseniorKeyword_5() { return cColorseniorKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//colorsenior+=[ColorSenior|Name]
		public Assignment getColorseniorAssignment_7() { return cColorseniorAssignment_7; }
		
		//[ColorSenior|Name]
		public CrossReference getColorseniorColorSeniorCrossReference_7_0() { return cColorseniorColorSeniorCrossReference_7_0; }
		
		//Name
		public RuleCall getColorseniorColorSeniorNameParserRuleCall_7_0_1() { return cColorseniorColorSeniorNameParserRuleCall_7_0_1; }
		
		//'cards'
		public Keyword getCardsKeyword_8() { return cCardsKeyword_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//cards+=Card*
		public Assignment getCardsAssignment_10() { return cCardsAssignment_10; }
		
		//Card
		public RuleCall getCardsCardParserRuleCall_10_0() { return cCardsCardParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class CardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Card");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameNameParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeCardTypeEnumRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Keyword cCardseniorKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cCardseniorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cCardseniorCardSeniorCrossReference_7_0 = (CrossReference)cCardseniorAssignment_7.eContents().get(0);
		private final RuleCall cCardseniorCardSeniorNameParserRuleCall_7_0_1 = (RuleCall)cCardseniorCardSeniorCrossReference_7_0.eContents().get(1);
		private final Keyword cRoomsKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cRoomsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cRoomsRoomParserRuleCall_10_0 = (RuleCall)cRoomsAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Card:
		//	name=Name '{'
		//	'type' ':' type=CardType
		//	'cardsenior' ':' cardsenior+=[CardSenior|Name]
		//	'rooms' '{'
		//	rooms+=Room*
		//	'}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=Name '{' 'type' ':' type=CardType 'cardsenior' ':' cardsenior+=[CardSenior|Name] 'rooms' '{' rooms+=Room* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//name=Name
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_0_0() { return cNameNameParserRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'type'
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//type=CardType
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//CardType
		public RuleCall getTypeCardTypeEnumRuleCall_4_0() { return cTypeCardTypeEnumRuleCall_4_0; }
		
		//'cardsenior'
		public Keyword getCardseniorKeyword_5() { return cCardseniorKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//cardsenior+=[CardSenior|Name]
		public Assignment getCardseniorAssignment_7() { return cCardseniorAssignment_7; }
		
		//[CardSenior|Name]
		public CrossReference getCardseniorCardSeniorCrossReference_7_0() { return cCardseniorCardSeniorCrossReference_7_0; }
		
		//Name
		public RuleCall getCardseniorCardSeniorNameParserRuleCall_7_0_1() { return cCardseniorCardSeniorNameParserRuleCall_7_0_1; }
		
		//'rooms'
		public Keyword getRoomsKeyword_8() { return cRoomsKeyword_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//rooms+=Room*
		public Assignment getRoomsAssignment_10() { return cRoomsAssignment_10; }
		
		//Room
		public RuleCall getRoomsRoomParserRuleCall_10_0() { return cRoomsRoomParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class RoomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Room");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameNameParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRoomseniorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRoomseniorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cRoomseniorRoomSeniorCrossReference_4_0 = (CrossReference)cRoomseniorAssignment_4.eContents().get(0);
		private final RuleCall cRoomseniorRoomSeniorNameParserRuleCall_4_0_1 = (RuleCall)cRoomseniorRoomSeniorCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Room:
		//	name=Name '{'
		//	'roomsenior' ':' roomsenior+=[RoomSenior|Name]
		//	/ *'freshmen' '{'
		//	        freshmen+=Freshman*
		//	    '}'* /
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=Name '{' 'roomsenior' ':' roomsenior+=[RoomSenior|Name] / *'freshmen' '{'
		//	        freshmen+=Freshman*
		//	    '}'* / '}'
		public Group getGroup() { return cGroup; }
		
		//name=Name
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_0_0() { return cNameNameParserRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'roomsenior'
		public Keyword getRoomseniorKeyword_2() { return cRoomseniorKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//roomsenior+=[RoomSenior|Name]
		public Assignment getRoomseniorAssignment_4() { return cRoomseniorAssignment_4; }
		
		//[RoomSenior|Name]
		public CrossReference getRoomseniorRoomSeniorCrossReference_4_0() { return cRoomseniorRoomSeniorCrossReference_4_0; }
		
		//Name
		public RuleCall getRoomseniorRoomSeniorNameParserRuleCall_4_0_1() { return cRoomseniorRoomSeniorNameParserRuleCall_4_0_1; }
		
		/// *'freshmen' '{'
		//	        freshmen+=Freshman*
		//	    '}'* / '}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class NameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Name");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Name:
		//	ID ID*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ID*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//ID*
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	public class ColorTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ColorType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBlackColorEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBlackColorBlackColorKeyword_0_0 = (Keyword)cBlackColorEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBlueColorEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBlueColorBlueColorKeyword_1_0 = (Keyword)cBlueColorEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cRedColorEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cRedColorRedColorKeyword_2_0 = (Keyword)cRedColorEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cWhiteColorEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cWhiteColorWhiteColorKeyword_3_0 = (Keyword)cWhiteColorEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cYellowColorEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cYellowColorYellowColorKeyword_4_0 = (Keyword)cYellowColorEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum ColorType:
		//	BlackColor |
		//	BlueColor |
		//	RedColor |
		//	WhiteColor |
		//	YellowColor;
		public EnumRule getRule() { return rule; }
		
		//BlackColor | BlueColor | RedColor | WhiteColor | YellowColor
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BlackColor
		public EnumLiteralDeclaration getBlackColorEnumLiteralDeclaration_0() { return cBlackColorEnumLiteralDeclaration_0; }
		
		//'BlackColor'
		public Keyword getBlackColorBlackColorKeyword_0_0() { return cBlackColorBlackColorKeyword_0_0; }
		
		//BlueColor
		public EnumLiteralDeclaration getBlueColorEnumLiteralDeclaration_1() { return cBlueColorEnumLiteralDeclaration_1; }
		
		//'BlueColor'
		public Keyword getBlueColorBlueColorKeyword_1_0() { return cBlueColorBlueColorKeyword_1_0; }
		
		//RedColor
		public EnumLiteralDeclaration getRedColorEnumLiteralDeclaration_2() { return cRedColorEnumLiteralDeclaration_2; }
		
		//'RedColor'
		public Keyword getRedColorRedColorKeyword_2_0() { return cRedColorRedColorKeyword_2_0; }
		
		//WhiteColor
		public EnumLiteralDeclaration getWhiteColorEnumLiteralDeclaration_3() { return cWhiteColorEnumLiteralDeclaration_3; }
		
		//'WhiteColor'
		public Keyword getWhiteColorWhiteColorKeyword_3_0() { return cWhiteColorWhiteColorKeyword_3_0; }
		
		//YellowColor
		public EnumLiteralDeclaration getYellowColorEnumLiteralDeclaration_4() { return cYellowColorEnumLiteralDeclaration_4; }
		
		//'YellowColor'
		public Keyword getYellowColorYellowColorKeyword_4_0() { return cYellowColorYellowColorKeyword_4_0; }
	}
	public class CardTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.CardType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBlueColorEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBlueColorBlueCardKeyword_0_0 = (Keyword)cBlueColorEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cGreenColorEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cGreenColorGreenCardKeyword_1_0 = (Keyword)cGreenColorEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cOrangeColorEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cOrangeColorOrangeCardKeyword_2_0 = (Keyword)cOrangeColorEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cYellowColorEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cYellowColorYellowCardKeyword_3_0 = (Keyword)cYellowColorEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum CardType:
		//	BlueColor='BlueCard' |
		//	GreenColor='GreenCard' |
		//	OrangeColor='OrangeCard' |
		//	YellowColor='YellowCard';
		public EnumRule getRule() { return rule; }
		
		//BlueColor='BlueCard' | GreenColor='GreenCard' | OrangeColor='OrangeCard' | YellowColor='YellowCard'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BlueColor='BlueCard'
		public EnumLiteralDeclaration getBlueColorEnumLiteralDeclaration_0() { return cBlueColorEnumLiteralDeclaration_0; }
		
		//'BlueCard'
		public Keyword getBlueColorBlueCardKeyword_0_0() { return cBlueColorBlueCardKeyword_0_0; }
		
		//GreenColor='GreenCard'
		public EnumLiteralDeclaration getGreenColorEnumLiteralDeclaration_1() { return cGreenColorEnumLiteralDeclaration_1; }
		
		//'GreenCard'
		public Keyword getGreenColorGreenCardKeyword_1_0() { return cGreenColorGreenCardKeyword_1_0; }
		
		//OrangeColor='OrangeCard'
		public EnumLiteralDeclaration getOrangeColorEnumLiteralDeclaration_2() { return cOrangeColorEnumLiteralDeclaration_2; }
		
		//'OrangeCard'
		public Keyword getOrangeColorOrangeCardKeyword_2_0() { return cOrangeColorOrangeCardKeyword_2_0; }
		
		//YellowColor='YellowCard'
		public EnumLiteralDeclaration getYellowColorEnumLiteralDeclaration_3() { return cYellowColorEnumLiteralDeclaration_3; }
		
		//'YellowCard'
		public Keyword getYellowColorYellowCardKeyword_3_0() { return cYellowColorYellowCardKeyword_3_0; }
	}
	
	private final CampElements pCamp;
	private final FreshmanElements pFreshman;
	private final ColorSeniorElements pColorSenior;
	private final CardSeniorElements pCardSenior;
	private final RoomSeniorElements pRoomSenior;
	private final OperativeOrganizerElements pOperativeOrganizer;
	private final ColorElements pColor;
	private final CardElements pCard;
	private final RoomElements pRoom;
	private final NameElements pName;
	private final ColorTypeElements eColorType;
	private final CardTypeElements eCardType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pCamp = new CampElements();
		this.pFreshman = new FreshmanElements();
		this.pColorSenior = new ColorSeniorElements();
		this.pCardSenior = new CardSeniorElements();
		this.pRoomSenior = new RoomSeniorElements();
		this.pOperativeOrganizer = new OperativeOrganizerElements();
		this.pColor = new ColorElements();
		this.pCard = new CardElements();
		this.pRoom = new RoomElements();
		this.pName = new NameElements();
		this.eColorType = new ColorTypeElements();
		this.eCardType = new CardTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Camp:
	//	'camp' name=ID
	//	'colorseniors' '{'
	//	colorseniors+=ColorSenior*
	//	'}'
	//	'cardseniors' '{'
	//	cardseniors+=CardSenior*
	//	'}'
	//	'roomseniors' '{'
	//	roomseniors+=RoomSenior*
	//	'}'
	//	'colors' '{'
	//	colors+=Color*
	//	'}';
	public CampElements getCampAccess() {
		return pCamp;
	}
	
	public ParserRule getCampRule() {
		return getCampAccess().getRule();
	}
	
	//Freshman:
	//	name=Name '{'
	//	'neptun' ':' neptun=STRING
	//	'color' ':' color=ColorType
	//	'card' ':' card=CardType
	//	'}';
	public FreshmanElements getFreshmanAccess() {
		return pFreshman;
	}
	
	public ParserRule getFreshmanRule() {
		return getFreshmanAccess().getRule();
	}
	
	//ColorSenior:
	//	name=Name '{'
	//	//'school' ':' school=STRING
	//	'year' ':' year=INT
	//	'color' ':' color=ColorType
	//	'inferiors' ':' inferiors+=[CardSenior|Name] (',' inferiors+=[CardSenior|Name])*
	//	'}';
	public ColorSeniorElements getColorSeniorAccess() {
		return pColorSenior;
	}
	
	public ParserRule getColorSeniorRule() {
		return getColorSeniorAccess().getRule();
	}
	
	//CardSenior:
	//	name=Name '{'
	//	//'school' ':' school=STRING
	//	'year' ':' year=INT
	//	'color' ':' color=ColorType
	//	'card' ':' card=CardType
	//	'superior' ':' superior+=[ColorSenior|Name]
	//	'inferiors' ':' inferiors+=[RoomSenior|Name] (',' inferiors+=[RoomSenior|Name])*
	//	'}';
	public CardSeniorElements getCardSeniorAccess() {
		return pCardSenior;
	}
	
	public ParserRule getCardSeniorRule() {
		return getCardSeniorAccess().getRule();
	}
	
	//RoomSenior:
	//	name=Name '{'
	//	//'school' ':' school=STRING
	//	'year' ':' year=INT
	//	'color' ':' color=ColorType
	//	'card' ':' card=CardType
	//	'superior' ':' superior+=[CardSenior|Name]
	//	'}';
	public RoomSeniorElements getRoomSeniorAccess() {
		return pRoomSenior;
	}
	
	public ParserRule getRoomSeniorRule() {
		return getRoomSeniorAccess().getRule();
	}
	
	//OperativeOrganizer:
	//	name=Name '{'
	//	//'school' ':' school=STRING
	//	'year' ':' year=INT
	//	'color' ':' color=ColorType
	//	'superior' ':' superior+=[OperativeOrganizer|Name]
	//	'inferiors' ':' inferiors+=[OperativeOrganizer|Name] (',' inferiors+=[OperativeOrganizer|Name])*
	//	'}';
	public OperativeOrganizerElements getOperativeOrganizerAccess() {
		return pOperativeOrganizer;
	}
	
	public ParserRule getOperativeOrganizerRule() {
		return getOperativeOrganizerAccess().getRule();
	}
	
	//Color:
	//	name=Name '{'
	//	'type' ':' type=ColorType
	//	'colorsenior' ':' colorsenior+=[ColorSenior|Name]
	//	'cards' '{'
	//	cards+=Card*
	//	'}'
	//	'}';
	public ColorElements getColorAccess() {
		return pColor;
	}
	
	public ParserRule getColorRule() {
		return getColorAccess().getRule();
	}
	
	//Card:
	//	name=Name '{'
	//	'type' ':' type=CardType
	//	'cardsenior' ':' cardsenior+=[CardSenior|Name]
	//	'rooms' '{'
	//	rooms+=Room*
	//	'}'
	//	'}';
	public CardElements getCardAccess() {
		return pCard;
	}
	
	public ParserRule getCardRule() {
		return getCardAccess().getRule();
	}
	
	//Room:
	//	name=Name '{'
	//	'roomsenior' ':' roomsenior+=[RoomSenior|Name]
	//	/ *'freshmen' '{'
	//	        freshmen+=Freshman*
	//	    '}'* /
	//	'}';
	public RoomElements getRoomAccess() {
		return pRoom;
	}
	
	public ParserRule getRoomRule() {
		return getRoomAccess().getRule();
	}
	
	//Name:
	//	ID ID*;
	public NameElements getNameAccess() {
		return pName;
	}
	
	public ParserRule getNameRule() {
		return getNameAccess().getRule();
	}
	
	//enum ColorType:
	//	BlackColor |
	//	BlueColor |
	//	RedColor |
	//	WhiteColor |
	//	YellowColor;
	public ColorTypeElements getColorTypeAccess() {
		return eColorType;
	}
	
	public EnumRule getColorTypeRule() {
		return getColorTypeAccess().getRule();
	}
	
	//enum CardType:
	//	BlueColor='BlueCard' |
	//	GreenColor='GreenCard' |
	//	OrangeColor='OrangeCard' |
	//	YellowColor='YellowCard';
	public CardTypeElements getCardTypeAccess() {
		return eCardType;
	}
	
	public EnumRule getCardTypeRule() {
		return getCardTypeAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
