/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Camp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Camp#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Camp#getColorseniors <em>Colorseniors</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Camp#getCardseniors <em>Cardseniors</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Camp#getRoomseniors <em>Roomseniors</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Camp#getColors <em>Colors</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCamp()
 * @model
 * @generated
 */
public interface Camp extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCamp_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Camp#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Colorseniors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ColorSenior}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Colorseniors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colorseniors</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCamp_Colorseniors()
   * @model containment="true"
   * @generated
   */
  EList<ColorSenior> getColorseniors();

  /**
   * Returns the value of the '<em><b>Cardseniors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.CardSenior}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cardseniors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardseniors</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCamp_Cardseniors()
   * @model containment="true"
   * @generated
   */
  EList<CardSenior> getCardseniors();

  /**
   * Returns the value of the '<em><b>Roomseniors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.RoomSenior}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Roomseniors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Roomseniors</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCamp_Roomseniors()
   * @model containment="true"
   * @generated
   */
  EList<RoomSenior> getRoomseniors();

  /**
   * Returns the value of the '<em><b>Colors</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Color}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Colors</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colors</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCamp_Colors()
   * @model containment="true"
   * @generated
   */
  EList<Color> getColors();

} // Camp
