/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Color</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Color#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Color#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Color#getColorsenior <em>Colorsenior</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Color#getCards <em>Cards</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColor()
 * @model
 * @generated
 */
public interface Color extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Color#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.ColorType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.ColorType
   * @see #setType(ColorType)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColor_Type()
   * @model
   * @generated
   */
  ColorType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Color#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.ColorType
   * @see #getType()
   * @generated
   */
  void setType(ColorType value);

  /**
   * Returns the value of the '<em><b>Colorsenior</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ColorSenior}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Colorsenior</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colorsenior</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColor_Colorsenior()
   * @model
   * @generated
   */
  EList<ColorSenior> getColorsenior();

  /**
   * Returns the value of the '<em><b>Cards</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Card}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cards</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cards</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getColor_Cards()
   * @model containment="true"
   * @generated
   */
  EList<Card> getCards();

} // Color
