/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Freshman</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Freshman#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Freshman#getNeptun <em>Neptun</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Freshman#getColor <em>Color</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Freshman#getCard <em>Card</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFreshman()
 * @model
 * @generated
 */
public interface Freshman extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFreshman_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Freshman#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Neptun</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Neptun</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Neptun</em>' attribute.
   * @see #setNeptun(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFreshman_Neptun()
   * @model
   * @generated
   */
  String getNeptun();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Freshman#getNeptun <em>Neptun</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Neptun</em>' attribute.
   * @see #getNeptun()
   * @generated
   */
  void setNeptun(String value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.ColorType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.ColorType
   * @see #setColor(ColorType)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFreshman_Color()
   * @model
   * @generated
   */
  ColorType getColor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Freshman#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.ColorType
   * @see #getColor()
   * @generated
   */
  void setColor(ColorType value);

  /**
   * Returns the value of the '<em><b>Card</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.CardType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Card</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Card</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.CardType
   * @see #setCard(CardType)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFreshman_Card()
   * @model
   * @generated
   */
  CardType getCard();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Freshman#getCard <em>Card</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Card</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.CardType
   * @see #getCard()
   * @generated
   */
  void setCard(CardType value);

} // Freshman
