/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CampImpl <em>Camp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CampImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCamp()
   * @generated
   */
  int CAMP = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMP__NAME = 0;

  /**
   * The feature id for the '<em><b>Colorseniors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMP__COLORSENIORS = 1;

  /**
   * The feature id for the '<em><b>Cardseniors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMP__CARDSENIORS = 2;

  /**
   * The feature id for the '<em><b>Roomseniors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMP__ROOMSENIORS = 3;

  /**
   * The feature id for the '<em><b>Colors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMP__COLORS = 4;

  /**
   * The number of structural features of the '<em>Camp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAMP_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FreshmanImpl <em>Freshman</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FreshmanImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFreshman()
   * @generated
   */
  int FRESHMAN = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRESHMAN__NAME = 0;

  /**
   * The feature id for the '<em><b>Neptun</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRESHMAN__NEPTUN = 1;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRESHMAN__COLOR = 2;

  /**
   * The feature id for the '<em><b>Card</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRESHMAN__CARD = 3;

  /**
   * The number of structural features of the '<em>Freshman</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FRESHMAN_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ColorSeniorImpl <em>Color Senior</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ColorSeniorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getColorSenior()
   * @generated
   */
  int COLOR_SENIOR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_SENIOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_SENIOR__YEAR = 1;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_SENIOR__COLOR = 2;

  /**
   * The feature id for the '<em><b>Inferiors</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_SENIOR__INFERIORS = 3;

  /**
   * The number of structural features of the '<em>Color Senior</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_SENIOR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CardSeniorImpl <em>Card Senior</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CardSeniorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCardSenior()
   * @generated
   */
  int CARD_SENIOR = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_SENIOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_SENIOR__YEAR = 1;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_SENIOR__COLOR = 2;

  /**
   * The feature id for the '<em><b>Card</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_SENIOR__CARD = 3;

  /**
   * The feature id for the '<em><b>Superior</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_SENIOR__SUPERIOR = 4;

  /**
   * The feature id for the '<em><b>Inferiors</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_SENIOR__INFERIORS = 5;

  /**
   * The number of structural features of the '<em>Card Senior</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_SENIOR_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RoomSeniorImpl <em>Room Senior</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RoomSeniorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRoomSenior()
   * @generated
   */
  int ROOM_SENIOR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_SENIOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_SENIOR__YEAR = 1;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_SENIOR__COLOR = 2;

  /**
   * The feature id for the '<em><b>Card</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_SENIOR__CARD = 3;

  /**
   * The feature id for the '<em><b>Superior</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_SENIOR__SUPERIOR = 4;

  /**
   * The number of structural features of the '<em>Room Senior</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_SENIOR_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.OperativeOrganizerImpl <em>Operative Organizer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.OperativeOrganizerImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOperativeOrganizer()
   * @generated
   */
  int OPERATIVE_ORGANIZER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIVE_ORGANIZER__NAME = 0;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIVE_ORGANIZER__YEAR = 1;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIVE_ORGANIZER__COLOR = 2;

  /**
   * The feature id for the '<em><b>Superior</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIVE_ORGANIZER__SUPERIOR = 3;

  /**
   * The feature id for the '<em><b>Inferiors</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIVE_ORGANIZER__INFERIORS = 4;

  /**
   * The number of structural features of the '<em>Operative Organizer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATIVE_ORGANIZER_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ColorImpl <em>Color</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ColorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getColor()
   * @generated
   */
  int COLOR = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR__TYPE = 1;

  /**
   * The feature id for the '<em><b>Colorsenior</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR__COLORSENIOR = 2;

  /**
   * The feature id for the '<em><b>Cards</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR__CARDS = 3;

  /**
   * The number of structural features of the '<em>Color</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CardImpl <em>Card</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CardImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCard()
   * @generated
   */
  int CARD = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD__TYPE = 1;

  /**
   * The feature id for the '<em><b>Cardsenior</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD__CARDSENIOR = 2;

  /**
   * The feature id for the '<em><b>Rooms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD__ROOMS = 3;

  /**
   * The number of structural features of the '<em>Card</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RoomImpl <em>Room</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RoomImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRoom()
   * @generated
   */
  int ROOM = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__NAME = 0;

  /**
   * The feature id for the '<em><b>Roomsenior</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM__ROOMSENIOR = 1;

  /**
   * The number of structural features of the '<em>Room</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.ColorType <em>Color Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.ColorType
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getColorType()
   * @generated
   */
  int COLOR_TYPE = 9;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.CardType <em>Card Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.CardType
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCardType()
   * @generated
   */
  int CARD_TYPE = 10;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Camp <em>Camp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Camp</em>'.
   * @see org.xtext.example.mydsl.myDsl.Camp
   * @generated
   */
  EClass getCamp();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Camp#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Camp#getName()
   * @see #getCamp()
   * @generated
   */
  EAttribute getCamp_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Camp#getColorseniors <em>Colorseniors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Colorseniors</em>'.
   * @see org.xtext.example.mydsl.myDsl.Camp#getColorseniors()
   * @see #getCamp()
   * @generated
   */
  EReference getCamp_Colorseniors();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Camp#getCardseniors <em>Cardseniors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cardseniors</em>'.
   * @see org.xtext.example.mydsl.myDsl.Camp#getCardseniors()
   * @see #getCamp()
   * @generated
   */
  EReference getCamp_Cardseniors();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Camp#getRoomseniors <em>Roomseniors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Roomseniors</em>'.
   * @see org.xtext.example.mydsl.myDsl.Camp#getRoomseniors()
   * @see #getCamp()
   * @generated
   */
  EReference getCamp_Roomseniors();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Camp#getColors <em>Colors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Colors</em>'.
   * @see org.xtext.example.mydsl.myDsl.Camp#getColors()
   * @see #getCamp()
   * @generated
   */
  EReference getCamp_Colors();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Freshman <em>Freshman</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Freshman</em>'.
   * @see org.xtext.example.mydsl.myDsl.Freshman
   * @generated
   */
  EClass getFreshman();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Freshman#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Freshman#getName()
   * @see #getFreshman()
   * @generated
   */
  EAttribute getFreshman_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Freshman#getNeptun <em>Neptun</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Neptun</em>'.
   * @see org.xtext.example.mydsl.myDsl.Freshman#getNeptun()
   * @see #getFreshman()
   * @generated
   */
  EAttribute getFreshman_Neptun();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Freshman#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see org.xtext.example.mydsl.myDsl.Freshman#getColor()
   * @see #getFreshman()
   * @generated
   */
  EAttribute getFreshman_Color();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Freshman#getCard <em>Card</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Card</em>'.
   * @see org.xtext.example.mydsl.myDsl.Freshman#getCard()
   * @see #getFreshman()
   * @generated
   */
  EAttribute getFreshman_Card();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ColorSenior <em>Color Senior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Color Senior</em>'.
   * @see org.xtext.example.mydsl.myDsl.ColorSenior
   * @generated
   */
  EClass getColorSenior();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ColorSenior#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.ColorSenior#getName()
   * @see #getColorSenior()
   * @generated
   */
  EAttribute getColorSenior_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ColorSenior#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see org.xtext.example.mydsl.myDsl.ColorSenior#getYear()
   * @see #getColorSenior()
   * @generated
   */
  EAttribute getColorSenior_Year();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ColorSenior#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see org.xtext.example.mydsl.myDsl.ColorSenior#getColor()
   * @see #getColorSenior()
   * @generated
   */
  EAttribute getColorSenior_Color();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.ColorSenior#getInferiors <em>Inferiors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Inferiors</em>'.
   * @see org.xtext.example.mydsl.myDsl.ColorSenior#getInferiors()
   * @see #getColorSenior()
   * @generated
   */
  EReference getColorSenior_Inferiors();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.CardSenior <em>Card Senior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Card Senior</em>'.
   * @see org.xtext.example.mydsl.myDsl.CardSenior
   * @generated
   */
  EClass getCardSenior();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CardSenior#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.CardSenior#getName()
   * @see #getCardSenior()
   * @generated
   */
  EAttribute getCardSenior_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CardSenior#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see org.xtext.example.mydsl.myDsl.CardSenior#getYear()
   * @see #getCardSenior()
   * @generated
   */
  EAttribute getCardSenior_Year();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CardSenior#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see org.xtext.example.mydsl.myDsl.CardSenior#getColor()
   * @see #getCardSenior()
   * @generated
   */
  EAttribute getCardSenior_Color();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.CardSenior#getCard <em>Card</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Card</em>'.
   * @see org.xtext.example.mydsl.myDsl.CardSenior#getCard()
   * @see #getCardSenior()
   * @generated
   */
  EAttribute getCardSenior_Card();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.CardSenior#getSuperior <em>Superior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Superior</em>'.
   * @see org.xtext.example.mydsl.myDsl.CardSenior#getSuperior()
   * @see #getCardSenior()
   * @generated
   */
  EReference getCardSenior_Superior();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.CardSenior#getInferiors <em>Inferiors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Inferiors</em>'.
   * @see org.xtext.example.mydsl.myDsl.CardSenior#getInferiors()
   * @see #getCardSenior()
   * @generated
   */
  EReference getCardSenior_Inferiors();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.RoomSenior <em>Room Senior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room Senior</em>'.
   * @see org.xtext.example.mydsl.myDsl.RoomSenior
   * @generated
   */
  EClass getRoomSenior();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.RoomSenior#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.RoomSenior#getName()
   * @see #getRoomSenior()
   * @generated
   */
  EAttribute getRoomSenior_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.RoomSenior#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see org.xtext.example.mydsl.myDsl.RoomSenior#getYear()
   * @see #getRoomSenior()
   * @generated
   */
  EAttribute getRoomSenior_Year();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.RoomSenior#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see org.xtext.example.mydsl.myDsl.RoomSenior#getColor()
   * @see #getRoomSenior()
   * @generated
   */
  EAttribute getRoomSenior_Color();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.RoomSenior#getCard <em>Card</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Card</em>'.
   * @see org.xtext.example.mydsl.myDsl.RoomSenior#getCard()
   * @see #getRoomSenior()
   * @generated
   */
  EAttribute getRoomSenior_Card();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.RoomSenior#getSuperior <em>Superior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Superior</em>'.
   * @see org.xtext.example.mydsl.myDsl.RoomSenior#getSuperior()
   * @see #getRoomSenior()
   * @generated
   */
  EReference getRoomSenior_Superior();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.OperativeOrganizer <em>Operative Organizer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operative Organizer</em>'.
   * @see org.xtext.example.mydsl.myDsl.OperativeOrganizer
   * @generated
   */
  EClass getOperativeOrganizer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.OperativeOrganizer#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.OperativeOrganizer#getName()
   * @see #getOperativeOrganizer()
   * @generated
   */
  EAttribute getOperativeOrganizer_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.OperativeOrganizer#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see org.xtext.example.mydsl.myDsl.OperativeOrganizer#getYear()
   * @see #getOperativeOrganizer()
   * @generated
   */
  EAttribute getOperativeOrganizer_Year();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.OperativeOrganizer#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see org.xtext.example.mydsl.myDsl.OperativeOrganizer#getColor()
   * @see #getOperativeOrganizer()
   * @generated
   */
  EAttribute getOperativeOrganizer_Color();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.OperativeOrganizer#getSuperior <em>Superior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Superior</em>'.
   * @see org.xtext.example.mydsl.myDsl.OperativeOrganizer#getSuperior()
   * @see #getOperativeOrganizer()
   * @generated
   */
  EReference getOperativeOrganizer_Superior();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.OperativeOrganizer#getInferiors <em>Inferiors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Inferiors</em>'.
   * @see org.xtext.example.mydsl.myDsl.OperativeOrganizer#getInferiors()
   * @see #getOperativeOrganizer()
   * @generated
   */
  EReference getOperativeOrganizer_Inferiors();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Color <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Color</em>'.
   * @see org.xtext.example.mydsl.myDsl.Color
   * @generated
   */
  EClass getColor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Color#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Color#getName()
   * @see #getColor()
   * @generated
   */
  EAttribute getColor_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Color#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Color#getType()
   * @see #getColor()
   * @generated
   */
  EAttribute getColor_Type();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Color#getColorsenior <em>Colorsenior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Colorsenior</em>'.
   * @see org.xtext.example.mydsl.myDsl.Color#getColorsenior()
   * @see #getColor()
   * @generated
   */
  EReference getColor_Colorsenior();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Color#getCards <em>Cards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cards</em>'.
   * @see org.xtext.example.mydsl.myDsl.Color#getCards()
   * @see #getColor()
   * @generated
   */
  EReference getColor_Cards();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Card <em>Card</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Card</em>'.
   * @see org.xtext.example.mydsl.myDsl.Card
   * @generated
   */
  EClass getCard();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Card#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Card#getName()
   * @see #getCard()
   * @generated
   */
  EAttribute getCard_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Card#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Card#getType()
   * @see #getCard()
   * @generated
   */
  EAttribute getCard_Type();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Card#getCardsenior <em>Cardsenior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Cardsenior</em>'.
   * @see org.xtext.example.mydsl.myDsl.Card#getCardsenior()
   * @see #getCard()
   * @generated
   */
  EReference getCard_Cardsenior();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Card#getRooms <em>Rooms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rooms</em>'.
   * @see org.xtext.example.mydsl.myDsl.Card#getRooms()
   * @see #getCard()
   * @generated
   */
  EReference getCard_Rooms();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Room <em>Room</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Room</em>'.
   * @see org.xtext.example.mydsl.myDsl.Room
   * @generated
   */
  EClass getRoom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Room#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Room#getName()
   * @see #getRoom()
   * @generated
   */
  EAttribute getRoom_Name();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Room#getRoomsenior <em>Roomsenior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Roomsenior</em>'.
   * @see org.xtext.example.mydsl.myDsl.Room#getRoomsenior()
   * @see #getRoom()
   * @generated
   */
  EReference getRoom_Roomsenior();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.ColorType <em>Color Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Color Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.ColorType
   * @generated
   */
  EEnum getColorType();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.myDsl.CardType <em>Card Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Card Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.CardType
   * @generated
   */
  EEnum getCardType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CampImpl <em>Camp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CampImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCamp()
     * @generated
     */
    EClass CAMP = eINSTANCE.getCamp();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAMP__NAME = eINSTANCE.getCamp_Name();

    /**
     * The meta object literal for the '<em><b>Colorseniors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAMP__COLORSENIORS = eINSTANCE.getCamp_Colorseniors();

    /**
     * The meta object literal for the '<em><b>Cardseniors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAMP__CARDSENIORS = eINSTANCE.getCamp_Cardseniors();

    /**
     * The meta object literal for the '<em><b>Roomseniors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAMP__ROOMSENIORS = eINSTANCE.getCamp_Roomseniors();

    /**
     * The meta object literal for the '<em><b>Colors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAMP__COLORS = eINSTANCE.getCamp_Colors();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FreshmanImpl <em>Freshman</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FreshmanImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFreshman()
     * @generated
     */
    EClass FRESHMAN = eINSTANCE.getFreshman();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRESHMAN__NAME = eINSTANCE.getFreshman_Name();

    /**
     * The meta object literal for the '<em><b>Neptun</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRESHMAN__NEPTUN = eINSTANCE.getFreshman_Neptun();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRESHMAN__COLOR = eINSTANCE.getFreshman_Color();

    /**
     * The meta object literal for the '<em><b>Card</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FRESHMAN__CARD = eINSTANCE.getFreshman_Card();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ColorSeniorImpl <em>Color Senior</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ColorSeniorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getColorSenior()
     * @generated
     */
    EClass COLOR_SENIOR = eINSTANCE.getColorSenior();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR_SENIOR__NAME = eINSTANCE.getColorSenior_Name();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR_SENIOR__YEAR = eINSTANCE.getColorSenior_Year();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR_SENIOR__COLOR = eINSTANCE.getColorSenior_Color();

    /**
     * The meta object literal for the '<em><b>Inferiors</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLOR_SENIOR__INFERIORS = eINSTANCE.getColorSenior_Inferiors();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CardSeniorImpl <em>Card Senior</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CardSeniorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCardSenior()
     * @generated
     */
    EClass CARD_SENIOR = eINSTANCE.getCardSenior();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD_SENIOR__NAME = eINSTANCE.getCardSenior_Name();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD_SENIOR__YEAR = eINSTANCE.getCardSenior_Year();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD_SENIOR__COLOR = eINSTANCE.getCardSenior_Color();

    /**
     * The meta object literal for the '<em><b>Card</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD_SENIOR__CARD = eINSTANCE.getCardSenior_Card();

    /**
     * The meta object literal for the '<em><b>Superior</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARD_SENIOR__SUPERIOR = eINSTANCE.getCardSenior_Superior();

    /**
     * The meta object literal for the '<em><b>Inferiors</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARD_SENIOR__INFERIORS = eINSTANCE.getCardSenior_Inferiors();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RoomSeniorImpl <em>Room Senior</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RoomSeniorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRoomSenior()
     * @generated
     */
    EClass ROOM_SENIOR = eINSTANCE.getRoomSenior();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM_SENIOR__NAME = eINSTANCE.getRoomSenior_Name();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM_SENIOR__YEAR = eINSTANCE.getRoomSenior_Year();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM_SENIOR__COLOR = eINSTANCE.getRoomSenior_Color();

    /**
     * The meta object literal for the '<em><b>Card</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM_SENIOR__CARD = eINSTANCE.getRoomSenior_Card();

    /**
     * The meta object literal for the '<em><b>Superior</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM_SENIOR__SUPERIOR = eINSTANCE.getRoomSenior_Superior();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.OperativeOrganizerImpl <em>Operative Organizer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.OperativeOrganizerImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOperativeOrganizer()
     * @generated
     */
    EClass OPERATIVE_ORGANIZER = eINSTANCE.getOperativeOrganizer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATIVE_ORGANIZER__NAME = eINSTANCE.getOperativeOrganizer_Name();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATIVE_ORGANIZER__YEAR = eINSTANCE.getOperativeOrganizer_Year();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATIVE_ORGANIZER__COLOR = eINSTANCE.getOperativeOrganizer_Color();

    /**
     * The meta object literal for the '<em><b>Superior</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATIVE_ORGANIZER__SUPERIOR = eINSTANCE.getOperativeOrganizer_Superior();

    /**
     * The meta object literal for the '<em><b>Inferiors</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATIVE_ORGANIZER__INFERIORS = eINSTANCE.getOperativeOrganizer_Inferiors();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ColorImpl <em>Color</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ColorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getColor()
     * @generated
     */
    EClass COLOR = eINSTANCE.getColor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR__NAME = eINSTANCE.getColor_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR__TYPE = eINSTANCE.getColor_Type();

    /**
     * The meta object literal for the '<em><b>Colorsenior</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLOR__COLORSENIOR = eINSTANCE.getColor_Colorsenior();

    /**
     * The meta object literal for the '<em><b>Cards</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLOR__CARDS = eINSTANCE.getColor_Cards();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CardImpl <em>Card</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CardImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCard()
     * @generated
     */
    EClass CARD = eINSTANCE.getCard();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD__NAME = eINSTANCE.getCard_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD__TYPE = eINSTANCE.getCard_Type();

    /**
     * The meta object literal for the '<em><b>Cardsenior</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARD__CARDSENIOR = eINSTANCE.getCard_Cardsenior();

    /**
     * The meta object literal for the '<em><b>Rooms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARD__ROOMS = eINSTANCE.getCard_Rooms();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RoomImpl <em>Room</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RoomImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRoom()
     * @generated
     */
    EClass ROOM = eINSTANCE.getRoom();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOM__NAME = eINSTANCE.getRoom_Name();

    /**
     * The meta object literal for the '<em><b>Roomsenior</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOM__ROOMSENIOR = eINSTANCE.getRoom_Roomsenior();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.ColorType <em>Color Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.ColorType
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getColorType()
     * @generated
     */
    EEnum COLOR_TYPE = eINSTANCE.getColorType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.CardType <em>Card Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.CardType
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCardType()
     * @generated
     */
    EEnum CARD_TYPE = eINSTANCE.getCardType();

  }

} //MyDslPackage
